#!/usr/bin/env python

""" Random test generation with content balancing. """

import argparse
import sys
from testgen import maketest

def parse_args(argv=None):
    """ Parse command line arguments.
    """
    parser = argparse.ArgumentParser(
        description="Randomly generate a test from an item bank.",
        epilog="""Tests are defined by a list of tags. Every item in the item bank is
        assigned one or more tags. The configuration file defines which items should be
        included in the test using these tags. Every entry in the configuration specifies
        a set of possible items using their tags and specifies how many of those items
        should be included in the test.""")
    parser.add_argument('bank_file', help='YAML file containing the item bank')
    parser.add_argument('config_file',
                        help='configuration YAML file defining test structure')
    parser.add_argument('-o', '--outfile', default='test',
                        help='name of the output file, without extension')
    parser.add_argument('--max_tries', default=10,
                        help='maximum number of times to try to generate a test')
    return vars(parser.parse_args(argv))

if __name__ == "__main__":
    maketest(**parse_args(sys.argv[1:]))
